version: '3'

services:
  teleoko:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "8082:8082"
    volumes:
      - ./config.json:/app/config.json
    networks:
      - teleoko-network

networks:
  teleoko-network:
    driver: bridge